version: '3.3'
services:
    web_server:
        build: ./server
        ports: 
            - "8080:8080"
        hostname: web-server

    vote_api:
        build: ./api
        ports:
            - "9090:9090"
        hostname: vote-api