version: '3.3'
services:
    web_server:
        build: ./server
        container_name: chara_web_server
        environment:
            KARI_SESSION_KEY: supersecretsessionkeyfortest
        ports: 
            - "8080:8080"
        hostname: web-server

    vote_api:
        build: ./api
        container_name: chara_vote_api
        ports:
            - "9090:9090"
        hostname: vote-api
        depends_on:
            - mysql

    result:
        build: ./result
        container_name: chara_result
        environment:
            KARI_SESSION_KEY: supersecretsessionkeyfortest
        ports:
            - "7070:7070"
        hostname: result_server
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: chara_mysql
        command: 
            - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
        # 中に入るのは $mysql --user=root --password=pass
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: sampledb
        ports: 
            - "3306:3306"
        volumes:
            - db-volume:/var/lib/mysql

    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - redis-volume:/data

volumes:
    db-volume:
    redis-volume: