apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-ranking-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character-ranking
  template:
    metadata:
      labels:
        app: character-ranking
        tier: development-api
    spec:
      containers:
      - name: k8s-app-api
        image: character_ranking_vote-api
        imagePullPolicy: Never
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: vote-api
  labels:
    app: character-ranking
spec:
  type:
    LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    # 以下のlabelがついているpodを対象にする
    app: character-ranking
    tier: development-api