apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-ranking-result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character-ranking
  template:
    metadata:
      labels:
        app: character-ranking
        tier: development-result
    spec:
      containers:
      - name: k8s-result
        image: character_ranking_result
        imagePullPolicy: Never
        ports:
        - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: character-ranking
spec:
  type:
    NodePort
  ports:
    - port: 7070
      targetPort: 7070
      protocol: TCP
  selector:
    # 以下のlabelがついているpodを対象にする
    app: character-ranking
    tier: development-result