apiVersion: v1
kind: Pod
metadata:
    name: k8s-testpod
    labels:
      app: character-ranking
spec:
    containers:
    - name: k8s-testpod
      image: golang:1.13
      imagePullPolicy: Never
      command:
        - sleep
        - "3600"
