apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-ranking-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character-ranking
  template:
    metadata:
      labels:
        app: character-ranking
        tier: development-web
    spec:
      containers:
      - name: k8s-web
        image: character_ranking_web_server
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: character-ranking
spec:
  type:
    NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    # 以下のlabelがついているpodを対象にする
    app: character-ranking
    tier: development-web